### ISSUE TITLE
Update to androidx.test.ext:junit:1.2.0 and androidx.test.espresso:3.6.0 io.mockk.proxy.MockKAgentException error occurred

### ISSUE THREAD

**Issue by dilkw** [android/android-test#2246]
### Description
The original androidx.test.ext:junit version is 1.1.5, and the original androidx.test.espresso:espresso-core version is 3.5.1

When I upgraded these two versions to 1.2.0 and 3.6.0 respectively and executed the test task, the following error occurred：

java.lang.NoSuchMethodError: No static method forceEnableAppTracing()V in class Landroidx/tracing/Trace; or its super classes (declaration of 'androidx.tracing.Trace' appears in /data/app/com.example.composeuitestdemo-5YC-laIuEkSizEk8-ehm7w==/base.apk!classes6.dex)
at androidx.test.platform.tracing.AndroidXTracer.enableTracing(AndroidXTracer.java:57)
at androidx.test.platform.tracing.Tracing.<init>(Tracing.java:53)
at androidx.test.platform.tracing.Tracing.<clinit>(Tracing.java:49)
at androidx.test.platform.tracing.Tracing.getInstance(Tracing.java:62)
at androidx.test.espresso.base.BaseLayerModule.providesTracing(BaseLayerModule.java:190)
at androidx.test.espresso.base.BaseLayerModule_ProvidesTracingFactory.providesTracing(BaseLayerModule_ProvidesTracingFactory.java:37)
at androidx.test.espresso.base.BaseLayerModule_ProvidesTracingFactory.get(BaseLayerModule_ProvidesTracingFactory.java:29)
at androidx.test.espresso.base.BaseLayerModule_ProvidesTracingFactory.get(BaseLayerModule_ProvidesTracingFactory.java:11)
at androidx.test.espresso.core.internal.deps.dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
at androidx.test.espresso.base.IdlingResourceRegistry_Factory.get(IdlingResourceRegistry_Factory.java:34)
at androidx.test.espresso.base.IdlingResourceRegistry_Factory.get(IdlingResourceRegistry_Factory.java:12)
at androidx.test.espresso.core.internal.deps.dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
at androidx.test.espresso.DaggerBaseLayerComponent$BaseLayerComponentImpl.idlingResourceRegistry(DaggerBaseLayerComponent.java:275)
at androidx.test.espresso.Espresso.<clinit>(Espresso.java:64)
at androidx.test.espresso.Espresso.onIdle(Espresso.java:378)
at androidx.compose.ui.test.junit4.EspressoLink_androidKt.runEspressoOnIdle(EspressoLink.android.kt:92)
at androidx.compose.ui.test.junit4.EspressoLink.runUntilIdle(EspressoLink.android.kt:79)
at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.runTest(ComposeUiTest.android.kt:320)
at androidx.compose.ui.test.junit4.AndroidComposeTestRule$apply$1.evaluate(AndroidComposeTestRule.android.kt:271)
at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:162)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:68)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:463)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2189)

AGP:8.5.0
Gradle:8.7

mockk version :
          mockk = "1.13.11"
          mockkAndroid = "1.13.11"

**Comment by TWiStErRob** [comment]
\+1 seeing tracing related errors for the first time ever in some of my repos too.

Example:
https://github.com/TWiStErRob/net.twisterrob.colorfilters/pull/332/checks?check_run_id=26633970200

If relevant: I have mockito-android on the classpath, but they're not used in these tests as far as I can see and remember.

**Comment by brettchabot** [comment]
Thanks for the report and sorry for the hassle.

Please see 'Known issues' here https://developer.android.com/jetpack/androidx/releases/test#monitor-1.7.0
 As a workaround, add an explicit 'implementation androidx.tracing:1.1.0' dependency.
