### ISSUE TITLE
No method shouldWaitForActivitiesToComplete() in androidx/test/runner/AndroidJUnitRunner

### ISSUE THREAD

**Issue by koral--** [android/android-test#472]
### Description
The following exception is thrown:
```    
java.lang.NoSuchMethodError: No virtual method shouldWaitForActivitiesToComplete()Z in class Landroidx/test/runner/AndroidJUnitRunner; or its super classes (declaration of 'androidx.test.runner.AndroidJUnitRunner' appears in /data/app/<stripped>.test-JkZIRodmjXzYle55nyZlZw==/base.apk)
        at androidx.test.runner.AndroidJUnitRunner.addListenersLegacyOrder(AndroidJUnitRunner.java:442)
        at androidx.test.runner.AndroidJUnitRunner.addListeners(AndroidJUnitRunner.java:423)
        at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:391)
        at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2189)
```
### Steps to Reproduce
`./gradlew connectedCheck`

### Expected Results
Tests should run

### Actual Results
Exception is thrown

### AndroidX Test and Android OS Versions
androidx.test:runner:1.3.0-alpha03
androidx.test.espresso:espresso-intents:3.3.0-alpha03
Worked fine on 1.3.0-alpha02 and 3.3.0-alpha02 respectively

Any Android OS Version.

**Comment by brettchabot** [comment]
Thanks for the report. My guess is your project is picking up an older version of androidx.test:monitor somehow.

Can you post your complete build.gradle file, or if that is not possible, check the output of 'gradle dependencies'. Thanks!

**Comment by koral--** [comment]
```    
    implementation(kotlin("stdlib-jdk7", Versions.kotlin))
    implementation("androidx.appcompat:appcompat:${Versions.appCompat}")
    implementation("com.jakewharton.timber:timber:${Versions.timber}")
    implementation("com.google.firebase:firebase-analytics:${Versions.firebaseAnalytics}")
    implementation("com.crashlytics.sdk.android:crashlytics:${Versions.crashlytics}")
    implementation("org.koin:koin-androidx-viewmodel:${Versions.koin}")
    implementation("com.jakewharton.threetenabp:threetenabp:${Versions.threetenabp}")
    implementation("com.github.piasy:BigImageViewer:${Versions.bigImageViewer}")
    implementation("com.github.piasy:GlideImageLoader:${Versions.bigImageViewer}")

    debugImplementation("pl.droidsonroids.foqa:foqa:${Versions.foqa}")
    debugImplementation("androidx.fragment:fragment-testing:${Versions.androidxFragmentTesting}")

    androidTestImplementation("androidx.test.ext:junit:${Versions.extJunit}")
    androidTestImplementation("org.koin:koin-test:${Versions.koin}")
    androidTestImplementation("com.willowtreeapps.assertk:assertk-jvm:${Versions.assertk}")
    androidTestImplementation("androidx.test:runner:${Versions.androidxTestRunner}")
    androidTestImplementation("org.junit.jupiter:junit-jupiter-api:${Versions.junit5}")
    androidTestImplementation("androidx.test:rules:${Versions.androidxTestRunner}")
    androidTestImplementation("androidx.test.espresso:espresso-intents:${Versions.espresso}")
    androidTestImplementation("de.mannodermaus.junit5:android-test-core:${Versions.junit5AndroidTest}")
    androidTestRuntimeOnly("de.mannodermaus.junit5:android-test-runner:${Versions.junit5AndroidTest}")
```
Versions:
```
object Versions {
    const val minSdk = 24
    const val compileSdk = 29
    const val buildTools = "29.0.2"
    const val appCompat = "1.1.0"
    const val extJunit = "1.1.2-alpha02"
    const val androidPlugin = "4.0.0-alpha04"
    const val versionsPlugin = "0.27.0"
    const val junit5Plugin = "1.5.2.0"
    const val appDistributionPlugin = "1.2.0"
    const val fabricPlugin = "1.31.2"
    const val gitPlugin = "4.0.0"
    const val googleServicesPlugin = "4.3.3"
    const val localizationPlugin = "1.0.17"
    const val kotlin = "1.3.61"
    const val detekt = "1.2.1"
    const val assertk = "0.20"
    const val mockito = "3.2.0"
    const val mockitoKotlin = "2.2.0"
    const val junit5 = "5.6.0-M1"
    const val foqa = "0.1.9"
    const val timber = "4.7.1"
    const val leakCanary = "2.0"
    const val firebaseAnalytics = "17.2.1"
    const val crashlytics = "2.10.1"
    const val junit5AndroidTest = "1.2.0"
    const val constraintLayout = "2.0.0-beta3"
    const val viewpagerdotsindicator = "4.1.2"
    const val viewpager2 = "1.0.0"
    const val koin = "2.1.0-alpha-6"
    const val coroutines = "1.3.2-1.3.60"
    const val materialComponents = "1.2.0-alpha02"
    const val androidxPreference = "1.1.0"
    const val androidxTestRunner = "1.3.0-alpha02"
    const val androidxCore = "1.2.0-rc01"
    const val androidxCoreRuntime = "2.1.0"
    const val androidxFragmentTesting = "1.2.0-rc02"
    const val navigationComponent = "2.2.0-rc02"
    const val viewmodel = "2.2.0-rc02"
    const val androidxFragment = "1.2.0-rc02"
    const val zxing = "4.0.2"
    const val carbon = "0.16.0.1"
    const val threetenabp = "1.2.1"
    const val threetenbp = "1.4.0"
    const val espresso = "3.3.0-alpha02"
    const val glide = "4.10.0"
    const val aboutLibraries = "7.0.4"
    const val bigImageViewer = "1.6.2"
}
```

**Comment by brettchabot** [comment]
I'm guessing the issue is 'de.mannodermaus.junit5:android-test-runner' has a strict dependency on androidx.test:monitor:1.2.0

Try adding the following
configurations.all {
    resolutionStrategy {
        force "androidx.test:monitor:${rootProject.androidxTestRunner}"
    }
}

I'd also suggest filing an issue against the de.mannodermaus.junit5 project, to see if they can relax their dependency specification

**Comment by koral--** [comment]
Thanks, I confirm that your workaround works. 
Issue in android junit5 repo linked above.

**Comment by koral--** [comment]
@brettchabot it seems that the source of strict dependency is androidx.fragment:fragment-testing, not junit5.

```
+--- androidx.fragment:fragment-testing:1.2.0-rc03
|    +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.50 -> 1.3.61
|    |    +--- org.jetbrains.kotlin:kotlin-stdlib-common:1.3.61
|    |    \--- org.jetbrains:annotations:13.0 -> 16.0.1
|    +--- androidx.test:core:1.2.0
|    |    +--- androidx.annotation:annotation:1.0.0 -> 1.1.0
|    |    +--- androidx.test:monitor:1.2.0
```

**Comment by Zingam** [comment]
@brettchabot 

Adding any of these:
```
    debugImplementation "androidx.fragment:fragment-testing:$fragmentVersion"
    implementation "androidx.test:core:$androidXTestCoreVersion"
```

causes in the Codelab Test template https://github.com/googlecodelabs/android-testing

```
2020-04-25 15:23:46.198 9845-9877/com.example.android.architecture.blueprints.todoapp E/AndroidRuntime: FATAL EXCEPTION: Instr: androidx.test.runner.AndroidJUnitRunner
    Process: com.example.android.architecture.blueprints.todoapp, PID: 9845
    java.lang.NoSuchMethodError: No virtual method shouldWaitForActivitiesToComplete()Z in class Landroidx/test/runner/AndroidJUnitRunner; or its super classes (declaration of 'androidx.test.runner.AndroidJUnitRunner' appears in /data/app/com.example.android.architecture.blueprints.todoapp.test-TzswKzRJ_OZa5_QA5tm9Nw==/base.apk)
        at androidx.test.runner.AndroidJUnitRunner.addListenersLegacyOrder(AndroidJUnitRunner.java:442)
        at androidx.test.runner.AndroidJUnitRunner.addListeners(AndroidJUnitRunner.java:423)
        at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:391)
        at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2189)
```
