### ISSUE TITLE
Tests fails to run after updating espresso to 3.5.0 because of tracing library issue

### ISSUE THREAD

**Issue by antonicg** [android/android-test#1623]
### Description

After bumping the espresso library to the 3.5.0 version all the tests are crashing because of an issue with the tracing library. We don't have tracing library in the project and the issue is not fixed after adding it either.

### Steps to Reproduce

Run a test with the last version of the library and the setup specified.

### Expected Results

The test run properly

### Actual Results

The test fails with the following message:

`Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/test/platform/tracing/Tracing`

### AndroidX Test and Android OS Versions

`androidx.test` -> 1.5.0
`androidx.test:orchestrator` -> 1.4.2
`androidx.test.ext:junit` -> 1.1.4

Android OS API 13 and 9

**Comment by utzcoz** [comment]
The AndroidX tracing is brought by AXT. Do your tests exist in a pure Java module or do you run these tests with Robolectric environment? If yes, you can check https://github.com/robolectric/robolectric/pull/7683 to add `@aar` to your implementation statement to let Gradle can find proper configuration of AndroidX tracing library.

**Comment by antonicg** [comment]
@utzcoz it is an android module but we are not running them with Robolectric, they are Espresso tests

**Comment by vramasam** [comment]
@utzcoz  Yes we are also facing same issue. It is an android module but we are not running them with Robolectric, they are Espresso tests. cc @antonicg

**Comment by TWiStErRob** [comment]
Can either of you please provide a longer stack trace.
Also @antonicg by "OS API 13" did you mean [OS 13 / API 33](https://apilevels.com/)?

**Comment by TWiStErRob** [comment]
I had a quick look based on the info provided above, and just setting up a normal Espresso test, everything works fine: https://github.com/TWiStErRob/repros/tree/master/espresso/tracing-not-found

`Tracing` class is in the `androidx.test:monitor:1.6.0` dependency. Based on `androidx.test -> 1.5.0` line in your report, I must assume that you might be doing something in a generalized way for `androidx.test` Maven group.

Here's the output of `gradlew :dependencies --configuration=debugAndroidTestRuntimeClasspath` on a project with only:
```gradle
dependencies {
	androidTestImplementation("androidx.test.espresso:espresso-core:3.5.0")
	androidTestImplementation("androidx.test.ext:junit:1.1.4")
```

<details><summary><code>debugAndroidTestRuntimeClasspath </code></summary>

```
debugAndroidTestRuntimeClasspath - Runtime classpath of compilation 'debugAndroidTest' (target  (androidJvm)).
+--- androidx.test.espresso:espresso-core:3.5.0
|    +--- androidx.annotation:annotation:1.2.0
|    +--- androidx.test:core:1.5.0
|    |    +--- androidx.annotation:annotation:1.2.0
|    |    +--- androidx.test:monitor:1.6.0
|    |    |    +--- androidx.annotation:annotation:1.2.0
|    |    |    +--- androidx.test:annotation:1.0.1
|    |    |    |    +--- androidx.annotation:annotation:1.2.0
|    |    |    |    \--- androidx.annotation:annotation-experimental:1.1.0
|    |    |    \--- androidx.tracing:tracing:1.0.0
|    |    |         \--- androidx.annotation:annotation:1.1.0 -> 1.2.0
|    |    +--- androidx.test.services:storage:1.4.2
|    |    |    +--- androidx.annotation:annotation:1.2.0
|    |    |    +--- androidx.test:monitor:1.6.0 (*)
|    |    |    +--- com.google.code.findbugs:jsr305:2.0.2
|    |    |    \--- androidx.test:annotation:1.0.1 (*)
|    |    +--- androidx.lifecycle:lifecycle-common:2.3.1
|    |    |    \--- androidx.annotation:annotation:1.1.0 -> 1.2.0
|    |    +--- androidx.tracing:tracing:1.0.0 (*)
|    |    +--- com.google.guava:listenablefuture:1.0
|    |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.7.10 -> 1.7.22
|    |    |    +--- org.jetbrains.kotlin:kotlin-stdlib-common:1.7.22
|    |    |    \--- org.jetbrains:annotations:13.0
|    |    \--- androidx.concurrent:concurrent-futures:1.1.0
|    |         +--- androidx.annotation:annotation:1.1.0 -> 1.2.0
|    |         \--- com.google.guava:listenablefuture:1.0
|    +--- androidx.test:runner:1.5.0
|    |    +--- androidx.annotation:annotation:1.2.0
|    |    +--- androidx.test:annotation:1.0.1 (*)
|    |    +--- androidx.test:monitor:1.6.0 (*)
|    |    +--- androidx.test.services:storage:1.4.2 (*)
|    |    +--- androidx.tracing:tracing:1.0.0 (*)
|    |    \--- junit:junit:4.13.2
|    |         \--- org.hamcrest:hamcrest-core:1.3
|    +--- androidx.test.espresso:espresso-idling-resource:3.5.0
|    +--- com.squareup:javawriter:2.1.1
|    +--- javax.inject:javax.inject:1
|    +--- org.hamcrest:hamcrest-library:1.3
|    |    \--- org.hamcrest:hamcrest-core:1.3
|    +--- org.hamcrest:hamcrest-integration:1.3
|    |    \--- org.hamcrest:hamcrest-library:1.3 (*)
|    +--- com.google.code.findbugs:jsr305:2.0.2
|    +--- org.jetbrains.kotlin:kotlin-stdlib:1.7.10 -> 1.7.22 (*)
|    \--- androidx.test:annotation:1.0.1 (*)
+--- androidx.test.ext:junit:1.1.4
|    +--- junit:junit:4.13.2 (*)
|    +--- androidx.test:core:1.5.0 (*)
|    +--- androidx.test:monitor:1.6.0 (*)
|    \--- androidx.annotation:annotation:1.2.0
+--- org.jetbrains.kotlin:kotlin-stdlib:{strictly 1.7.22} -> 1.7.22 (c)
+--- org.jetbrains.kotlin:kotlin-stdlib-common:{strictly 1.7.22} -> 1.7.22 (c)
\--- org.jetbrains:annotations:{strictly 13.0} -> 13.0 (c)
```

</details>

Compare it with your own output, I suspect there'll be a line in there that says:
```
androidx.test:monitor:1.6.0 -> 1.5.0
```

<details><summary>I was able to reproduce the error:</summary>

```
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/test/platform/tracing/Tracing;
at androidx.test.espresso.base.BaseLayerModule.providesTracing(BaseLayerModule.java:1)
at androidx.test.espresso.base.BaseLayerModule_ProvidesTracingFactory.providesTracing(BaseLayerModule_ProvidesTracingFactory.java:1)
at androidx.test.espresso.base.BaseLayerModule_ProvidesTracingFactory.get(BaseLayerModule_ProvidesTracingFactory.java:1)
at androidx.test.espresso.base.BaseLayerModule_ProvidesTracingFactory.get(BaseLayerModule_ProvidesTracingFactory.java:2)
at androidx.test.espresso.core.internal.deps.dagger.internal.DoubleCheck.get(DoubleCheck.java:6)
at androidx.test.espresso.base.IdlingResourceRegistry_Factory.get(IdlingResourceRegistry_Factory.java:1)
at androidx.test.espresso.base.IdlingResourceRegistry_Factory.get(IdlingResourceRegistry_Factory.java:2)
at androidx.test.espresso.core.internal.deps.dagger.internal.DoubleCheck.get(DoubleCheck.java:6)
at androidx.test.espresso.DaggerBaseLayerComponent$BaseLayerComponentImpl.idlingResourceRegistry(DaggerBaseLayerComponent.java:1)
at androidx.test.espresso.Espresso.<clinit>(Espresso.java:3)
at androidx.test.espresso.Espresso.onView(Espresso.java:1)
at com.example.MyActivityTest.test(MyActivityTest.kt:20)
... 32 trimmed
Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.test.platform.tracing.Tracing" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/system/framework/android.test.mock.jar", zip file "/system/framework/android.test.base.jar", zip file "/data/app/~~-SmRzbBw0Y14UzConbPunA==/com.example.test-igwuKDcLNkOzCIeB_uEvjw==/base.apk", zip file "/data/app/~~vD-gD020QGut8ai_sJrUsA==/com.example-o2dppHzKEYQT5I3zKXeJwg==/base.apk"],nativeLibraryDirectories=[/data/app/~~-SmRzbBw0Y14UzConbPunA==/com.example.test-igwuKDcLNkOzCIeB_uEvjw==/lib/x86_64, /data/app/~~vD-gD020QGut8ai_sJrUsA==/com.example-o2dppHzKEYQT5I3zKXeJwg==/lib/x86_64, /system/lib64, /system_ext/lib64]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
... 45 more
```

</details>

but I needed to jump through some hoops and literally force a wrong version:
```gradle
// Make it fail: don't do this in production!
configurations.all {
	resolutionStrategy {
		eachDependency {
			if (requested.group == "androidx.test") {
				when (requested.name) {
					"annotation" -> useVersion("1.0.1")
					"orchestrator" -> useVersion("1.4.2")
					else -> useVersion("1.5.0")
				}
			}
		}
	}
}
```

If you use the above or `force()` or `exclude`, make sure you migrate away from those and let Gradle do it's dependency conflict resolution to pick the right versions.

**Comment by brettchabot** [comment]
Can you provide more details on the full specific set of androidx.* dependencies in both the implementation* and androidTestImplementation targets. 

I'm found some scenarios where an older dependency transitively gets included in the 'implementation' targets, and overrides the newer dependencies being introduced in androidTestImplementation targets

**Comment by TWiStErRob** [comment]
Tip: `gradlew :module:dependencyInsight --configuration=debugAndroidTestRuntimeClasspath --dependency=androidx.test:monitor` will tell you why a specific version was selected.

**Comment by antonicg** [comment]
@TWiStErRob were right, we were using a variable set as 1.5.0 for some `androidx.test` libraries and `androidx.test:monitor` was one of them. Also we were forcing to this version for some legacy reason. So, all your assumptions were right.
Thank you so much for your deeply investigation, it solved the issue and I also took some learnings from here ❤️.

**Comment by TWiStErRob** [comment]
@vramasam ?

**Comment by vramasam** [comment]
> @vramasam ?

Yes it worked for us. we are also forcing version 1.5.0 for some legacy reason Thank you @TWiStErRob .
