### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by bohsen**
### Overview

Improve CONTRIBUTING.md to make it easier for others to get started.

### Proposed Changes

*   Improve Building and Testing section to make it clear that Windows and Mac can be used for building and testing also
*   Remove Bazel version 2.2.0 recommendation as the project builds with newest version 3.5.0
*   Improve One Time Setup section:
    Update `Install the [Android SDK]` paragraph with correct build-tools versions
*   Move IDE Setup section up and improve IDE Setup instructions (specifically the instructions on Bazel intellij plugin setup - see [this](https://github.com/bazelbuild/intellij/issues/230) for context)
*   Added troubleshooting section about unresolved imports

### CODE REVIEW

**Comment by TWiStErRob** [comment]
Nice!

File: CONTRIBUTING.md [hunk 1]
```diff
@@ -19,28 +19,46 @@ again.
...
+    `./tools/bin/sdkmanager --install 'build-tools;30.0.2'
+    'platforms;android-30' 'emulator' 'platform-tools'
     'system-images;android-19;default;x86'
     'system-images;android-21;default;x86'
     'system-images;android-22;default;x86'
     'system-images;android-23;default;x86'`
-*   Set the ANDROID_HOME environment variable to point to the SDK install
-    location. eg `export ANDROID_HOME=/home/$USER/Android/Sdk`
+*   Set the `ANDROID_HOME` environment variable to point to the SDK install
+    location. eg `export ANDROID_HOME=/Users/$USER/Library/Android/sdk`
```
Comment (brettchabot) [inline CONTRIBUTING.md:45]: WDYT about giving both canonical Linux and mac install paths: such

Set the `ANDROID_HOME` environment variable to point to the SDK install
    location. For example
    * On Linux: `export ANDROID_HOME=/home/$USER/Android/Sdk`
    * On Mac: `export ANDROID_HOME=/Users/$USER/Library/Android/sdk`

File: CONTRIBUTING.md [hunk 2]
```diff
@@ -19,28 +19,46 @@ again.
...
+supports Windows and Mac, so it's possible to build and run the robolectric tests
+on Windows and Mac also.
 
 ### One time setup
 
 *   [Fork](https://help.github.com/articles/fork-a-repo/) and
     [clone](https://help.github.com/articles/cloning-a-repository/) the
     [AndroidX Test repo](https://github.com/android/android-test)
 *   Install [bazel](https://docs.bazel.build/versions/master/install.html).
-    Version 2.2.0 is recommended. Ensure your environment meets the following
```
Comment (brettchabot) [inline CONTRIBUTING.md:30]: I'd like to retain a specific version recommendation here. Bazel unfortunately has been making frequent breaking changes, and I don't want to recommend a version we haven't tested. 

CI is still using bazel 2.2.0, but we can/should look into upgrading to 3.5.0

File: CONTRIBUTING.md [hunk 3]
```diff
@@ -19,28 +19,46 @@ again.
 
 AndroidX Test uses the [bazel](https://bazel.build) build system.
 
-Currently only Linux is supported.
+Currently Linux is needed for building/running tests on emulators. Bazel itself
```
Comment (brettchabot) [inline CONTRIBUTING.md:22]: I'm concerned this updated description is misleading.

We can only officially recommend linux, since that is the only configuration that is tested. As well doing the full maven artifact build also requires linux. 

WDYT about rephrasing as follows:

- Currently only Linux is fully supported. For Mac ands windows users, you may be able to build and run the Robolectric tests.

File: CONTRIBUTING.md [hunk 4]
```diff
@@ -19,28 +19,46 @@ again.
...
+    For instrumentation testing on Linux make sure your environment meets the following
     [prerequisites](https://docs.bazel.build/versions/master/android-instrumentation-test.html#prerequisites)
 *   Install [maven](http://maven.apache.org/install.html) and make it available
     on PATH.
 *   Install the [Android SDK](https://developer.android.com/studio/install) and
     run the following command to ensure you have the necessary components:
-    `./tools/bin/sdkmanager --install 'build-tools;29.0.3'
-    'platforms;android-29' 'emulator' 'platform-tools'
+    `./tools/bin/sdkmanager --install 'build-tools;30.0.2'
+    'platforms;android-30' 'emulator' 'platform-tools'
```
Comment (brettchabot) [inline CONTRIBUTING.md:39]: nice catch thanks!

File: CONTRIBUTING.md [hunk 5]
```diff
@@ -68,15 +86,35 @@ To run all the robolectric local tests (and thus replicate the Google Cloud
...
+    )
+    ```
+
+2. Something might be wrong with `ANDROID_HOME` environment variable setup. Try adding the path of 
+the android-sdk to the `WORKSPACE` file:
+
+    ```bazel
+    android_sdk_repository(
+        ...
+        path = "/Users/$USER/Library/Android/sdk",
```
Comment (brettchabot) [inline CONTRIBUTING.md:114]: I am wary of recommending local modifications to the workspace. Is another possible workaround to launch studio from a terminal with that environment variable set?

File: CONTRIBUTING.md (hunk 1 above)
Comment (bohsen) [reply CONTRIBUTING.md:45]: I like it. I wonder what it is on Windows. i'll find out and add it.

File: CONTRIBUTING.md (hunk 3 above)
Comment (bohsen) [reply CONTRIBUTING.md:22]: I definitely like your wording better. I'll rephrase it.

File: CONTRIBUTING.md (hunk 2 above)
Comment (bohsen) [reply CONTRIBUTING.md:30]: I'll add it back.

File: CONTRIBUTING.md (hunk 5 above)
Comment (bohsen) [reply CONTRIBUTING.md:114]: > I am wary of recommending local modifications to the workspace

This is a troubleshooting section and I don't believe anyone would consider them recommendations. IMHO I think it's a viable addition to the doc.

I've searched for a better solution, but I keep coming back to this. Used it on all three Macs I use for work and all of them required this, to resolve the imports.

The official way (and recommended way AFAIK) is to setup your ANDROID_HOME environment variable and then bazel should use this when syncing, but I just couldn't get this to work. Why it doesn't I can't say, but this is my experience from the past couple of days and multiple tries on setting this up.

> Is another possible workaround to launch studio from a terminal

Wouldn't this be just as bad as the mentioned workaround?

File: CONTRIBUTING.md (hunk 1 above)
Comment (TWiStErRob) [reply CONTRIBUTING.md]: oops, just saw this looking at https://stackoverflow.com/q/26739114/253468 the default is `%HOMEPATH%\AppData\Local\Android\sdk`.
